### ISSUE TITLE
Unable to run the assignment

### ISSUE THREAD

**Issue by LcTwisk** [descorp/GiphyAPI#1]
Hi @descorp!
This morning I was looking into your assignment. So far it looks good but I couldn't get it to run because of the following problems:
- The `GiphyAPI` and `ApiProvider` frameworks are not correctly linked to `GiphyDemo` (not that important, can fix it myself)
- `config.plist` is missing in the repo. Can you provide me one? (you can leave the API key out if you want 😉).

Thanks!

**Comment by descorp** [comment]
Hi @LcTwisk

Oops, I have cleared up history to hide "sensitive data", and seems like I forget to push it 😥
I don't have my laptop around, but it should be like this:
        
      <?xml version="1.0" encoding="UTF-8"?>
      <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
      <plist version="1.0">
      <dict>
	      <key>Common</key>
	      <dict>
		      <key>AppKey</key>
		      <string>{API_KEY}</string>
		      <key>Version</key>
		      <string>v1</string>
	              <key>Url</key>
		      <string>http://api.giphy.com</string>
		      </dict>
      </dict>
      </plist>
